### ISSUE TITLE
기업은행에서 갱신한 공인인증서의 개인 키가 정상적으로 인식되지 않습니다.

### ISSUE THREAD

**Issue by youngminz** [bandoche/PyPinkSign#7]
안녕하세요, 프로젝트를 오픈 소스로 공개해 주셔서 무척 감사합니다. 소스 코드를 받아서 사용해 보던 중 더 이상 진행이 불가하여 이슈를 남깁니다. 

기업은행에서 새로 갱신한 공인인증서를 pypinksign 으로 인식해 보고 있는데 정상적으로 로드가 되지 않습니다. 갱신하기 전에는 인식이 잘 되었었는데 갱신을 하고 보니 잘 인식이 안되는군요. 뭔가 인증서의 레이아웃이 이전과 달라진 것 같아 수정해 보았습니다. (master 소스 기준으로 하였으며, python 3.6 입니다)

`load_prikey` 함수 내부의 `der` 변수를 출력해 보면 다음과 같이 출력됩니다.

```
Sequence:
 field-0=Sequence:
  field-0=1.2.840.113549.1.5.13
  field-1=SequenceOf:
   Sequence:
    field-0=1.2.840.113549.1.5.12
    field-1=Sequence:
     field-0=0xe20b7ce64655744c
     field-1=2048

   Sequence:
    field-0=1.2.410.200004.1.4
    field-1=0x8fecc7eb1d98bc596ab156733d658d71


 field-1=0x4febf75d ... <너무 길어서 생략하였습니다. 나머지 길이는 2520자입니다.>
```

이렇게 나와서, pypinksign.py 의 load_prikey 함수를 다음처럼 수정해 보았습니다. (인덱스 들과 `iv` 값 수정)

```py

algorithm_type = der[0][1][1][0].asTuple()

if algorithm_type not in (ID_SEED_CBC_WITH_SHA1, ID_SEED_CBC):
    raise ValueError("prikey is not correct K-PKI private key file")

salt = der[0][1][0][1][0].asOctets()  # salt for pbkdf#5
iter_cnt = int(der[0][1][0][1][1])  # usually 2048
cipher_key = der[1].asOctets()  # encryped private key
dk = pbkdf1(self.prikey_password, salt, iter_cnt, 20)
k = dk[:16]
div = hashlib.sha1(dk[16:20]).digest()

# IV for SEED-CBC has dependency on Algorithm type (Old-style K-PKI or Renewal)
if algorithm_type == ID_SEED_CBC_WITH_SHA1:
    iv = div[:16]
else:
    iv = b"0123456789012345"
```

이렇게 변경하자, 다음과 같이 패딩이 맞지 않다는 오류가 발생하였습니다.

```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    pypinksign.PinkSign(pubkey_path=..., prikey_path=..., prikey_password=...)
  File "pypinksign.py", line 91, in __init__
    self.load_prikey()
  File "pypinksign.py", line 161, in load_prikey
    prikey_data = seed_cbc_128_decrypt(k, cipher_key, iv)
  File "pypinksign.py", line 460, in seed_cbc_128_decrypt
    unpadded_text += unpadder.finalize()
  File ".../site-packages/cryptography/hazmat/primitives/padding.py", line 144, in finalize
    lib.Cryptography_check_pkcs7_padding)
  File ".../site-packages/cryptography/hazmat/primitives/padding.py", line 89, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.
```

이 이후로는 어디를 손을 대야 할지 감이 잡히지를 않습니다. 어떻게 수정해야 할지 힌트라도 공유해주시면 너무 감사하겠습니다..!

---

추가: `openssl asn1parse -in /signPri.key -inform der` 으로 출력된 결과입니다. PBKDF1 대신 PBKDF2가 보이는데 이것이 단서일 수 있을까요??

```
    0:d=0  hl=4 l=1342 cons: SEQUENCE
    4:d=1  hl=2 l=  72 cons: SEQUENCE
    6:d=2  hl=2 l=   9 prim: OBJECT            :PBES2
   17:d=2  hl=2 l=  59 cons: SEQUENCE
   19:d=3  hl=2 l=  27 cons: SEQUENCE
   21:d=4  hl=2 l=   9 prim: OBJECT            :PBKDF2
   32:d=4  hl=2 l=  14 cons: SEQUENCE
   34:d=5  hl=2 l=   8 prim: OCTET STRING      [HEX DUMP]:E20B7CE64655744C
   44:d=5  hl=2 l=   2 prim: INTEGER           :0800
   48:d=3  hl=2 l=  28 cons: SEQUENCE
   50:d=4  hl=2 l=   8 prim: OBJECT            :seed-cbc
   60:d=4  hl=2 l=  16 prim: OCTET STRING      [HEX DUMP]:8FECC7EB1D98BC596AB156733D658D71
   78:d=1  hl=4 l=1264 prim: OCTET STRING      [HEX DUMP]:4FEBF75D  ... <너무 길어서 생략하였습니다. 나머지 길이는 2520자입니다.>
```

**Comment by bandoche** [comment]
안녕하세요.
private key 양식이 바뀌었을 일은 잘 없을 것 같은데 최근에 수정했던 코드가 제대로 반영 못했을 수 있을 것 같습니다. 
ValueError: Invalid padding bytes. 의 경우 복호화에 실패한 경우 발생하고 보통은 비밀번호가 틀려서일 수도 있습니다. 하지만 `algorithm_type` 을 올바르게 인식하지 못하였을 경우 Iv값이 잘못되어 실패될 수도 있기는 한데 어느쪽인지는 모르겠네요. 저도 최근에 파일 하나가 잘 인식이 안되어서 더 못봤는데 같은 문제일수도 있을 것 같습니다.

말씀하신 것 처럼 PBKDF2의 이슈일 수도 있겠습니다. 
https://rootca.kisa.or.kr/kcac/down/TechSpec/2.3-Encryption%20Algorithm%20Scheme%20Specification.pdf 여기서는 PBKDF1에 대해만 다룬거같은데 2에 대한 부분도 처리가 필요하겠네요.

**Comment by youngminz** [comment]
넵, 확인 감사합니다. 시간이 될 때 조금 더 파보겠습니다. 감사합니다. ^^

2019년 7월 19일 (금) 오후 12:27, Jung Sang-jun <notifications@github.com>님이 작성:

**Comment by ghost** [comment]
국민은행 공인인증서가 동일한 오류가 나던데 혹시 pbes2 미처리 문제 아닌가요?

**Comment by youngminz** [comment]
네 해당 문제가 맞는 듯 합니다. PBES2 대로 구현해 보니 정상적으로 복호화 되는 것을 확인하였습니다.

**Comment by youngminz** [comment]
PBES2 스킴을 지원할 수 있도록 코드를 수정하였습니다. 인식이 안 되는 파일에 대한 복호화가 정상적으로 이루어지는지 확인 부탁드립니다!

**Comment by bandoche** [comment]
프로젝트에 도움 주셔서 매우 감사합니다.

**Comment by youngminz** [comment]
넵 :-) 즐거웠습니다!
